### ISSUE TITLE
Module to contain loop for forward simulation

### ISSUE THREAD

**Issue by Laura7089** [Carst-model/carst#6]
Loop between start + end time:
- Diffusion
- Carbonate
- Sea level
- Output?

**Comment by Edward70891** [comment]
Rudimentary implementation at e6a1d9a2c85fdab279e2109e553ce18e9d941e5.

**Comment by Edward70891** [comment]
Partially implemented in #13

**Comment by Edward70891** [comment]
a5f64ab25b6ad903ea8fc6b180c0c7bb53646f84 <- further progress

**Comment by Laura7089** [comment]
Planning changed, looping will now be carried out outside of carst (ie. by the calling script). A wrapper script may be included in the future to increase user friendliness.
